name: goldcity
description: "A new Flutter project."

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins: 
    sdk: flutter  



  cupertino_icons: ^1.0.2
  # state management
  flutter_mobx: ^2.0.0
  mobx: ^2.0.1
  provider: ^6.0.4
  build_runner: ^2.3.2
  json_annotation: ^4.0.1
  dio: ^5.4.2+1
  json_serializable: ^6.5.4
  mobx_codegen: ^2.0.1+3
  easy_localization: ^3.0.5
  gap: ^3.0.1
  dismissible_page: ^1.0.2
  google_maps_flutter: ^2.6.0
  get_it: ^7.6.0
  either_dart: ^0.4.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  video_player: ^2.8.6
  flutter_svg: ^2.0.10+1
  salomon_bottom_bar: ^3.3.2
  flutter_animate: ^4.5.0
  flutter_carousel_widget: ^2.2.0
  shared_preferences: ^2.2.3
  share_plus: ^9.0.0
  url_launcher: ^6.3.0
  google_maps_flutter_web: ^0.5.8
  go_router: ^14.2.0
  transparent_image: ^2.0.1
  webviewx_plus: ^0.5.0
  giffy_dialog: ^2.1.0
  firebase_core: ^3.1.1
  firebase_messaging: ^15.0.4
  flutter_notification_channel: ^2.0.0
  animated_text_kit: ^4.2.2
  app_links: ^6.1.4
  cool_dropdown: ^2.1.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/translations/    
    - assets/image/logo.png    
    - assets/video/trailer.mp4    
  fonts:
    - family: Encode
      fonts:
        - asset: assets/font/encode/encode-black.ttf
          weight: 900
        - asset: assets/font/encode/encode-extra-bold.ttf
          weight: 800
        - asset: assets/font/encode/encode-bold.ttf
          weight: 700
        - asset: assets/font/encode/encode-semi-bold.ttf
          weight: 600
        - asset: assets/font/encode/encode-medium.ttf
          weight: 500
        - asset: assets/font/encode/encode-regular.ttf
          weight: 400
        - asset: assets/font/encode/encode-light.ttf
          weight: 300
        - asset: assets/font/encode/encode-thin.ttf
          weight: 200
        - asset: assets/font/encode/encode-extra-light.ttf
          weight: 100