name: goldcity
description: "A new Flutter project."

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2
  # state management
  flutter_mobx: ^2.0.0
  mobx: ^2.0.1
  provider: ^6.0.4
  build_runner: ^2.3.2
  json_annotation: ^4.0.1
  dio: ^5.4.2+1
  json_serializable: ^6.5.4
  mobx_codegen: ^2.0.1+3
  easy_localization: ^3.0.5
  gap: ^3.0.1
  dismissible_page: ^1.0.2
  google_maps_flutter: ^2.6.0
  get_it: ^7.6.0
  either_dart: ^0.4.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/translations/    

  fonts:
    - family: Encode
      fonts:
        - asset: assets/font/encode/encode-black.ttf
          weight: 900
        - asset: assets/font/encode/encode-extra-bold.ttf
          weight: 800
        - asset: assets/font/encode/encode-bold.ttf
          weight: 700
        - asset: assets/font/encode/encode-semi-bold.ttf
          weight: 600
        - asset: assets/font/encode/encode-medium.ttf
          weight: 500
        - asset: assets/font/encode/encode-regular.ttf
          weight: 400
        - asset: assets/font/encode/encode-light.ttf
          weight: 300
        - asset: assets/font/encode/encode-thin.ttf
          weight: 200
        - asset: assets/font/encode/encode-extra-light.ttf
          weight: 100
