// ignore_for_file: constant_identifier_names, camel_case_types

enum APPLICATION_COLOR {
  GOLD,
  TITLE,
  SUBTITLE,
  BACKGROUND_COLOR,
  OVERLAY_COLOR,
  DARK,
  LIGHT,
  CLOSE_BACKGROUND_COLOR,
  EXTRA_CLOSE_BACKGROUND_COLOR,
  OPPOSITE_COLOR,
  GREEN,
  RED,
  BLUE,
}

enum FONT_SIZE {
  DISPLAY_LARGE,
  DISPLAY_MEDIUM,
  DISPLAY_SMALL,
  HEADLINE_LARGE,
  HEADLINE_MEDIUM,
  HEADLINE_SMALL,
  TITLE_LARGE,
  TITLE_MEDIUM,
  TITLE_SMALL,
  BODY_LARGE,
  BODY_MEDIUM,
  BODY_SMALL,
  LABEL_LARGE,
  LABEL_MEDIUM,
  LABEL_SMALL,
}
