// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: "AIzaSyA-okPckRFVoe6-NK0F1Dl_BJLEqNlwKLs",
    appId: '1:941064344872:android:6b3d6a37cd120548d36c1d',
    messagingSenderId: '941064344872',
    projectId: "gold-city-9d670",
    storageBucket: "gold-city-9d670.appspot.com",
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: "AIzaSyA-okPckRFVoe6-NK0F1Dl_BJLEqNlwKLs",
    appId: '1:941064344872:ios:1ae7f6541b8a7ddcd36c1d',
    messagingSenderId: '941064344872',
    projectId: "gold-city-9d670",
    storageBucket: "gold-city-9d670.appspot.com",
    iosClientId:
        '706961598879-cu18pfgmiq07um4bnub182fr52kghb9q.apps.googleusercontent.com',
    iosBundleId: 'com.goldcity.goldcityMobil',
  );
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyA-okPckRFVoe6-NK0F1Dl_BJLEqNlwKLs",
    authDomain: "gold-city-9d670.firebaseapp.com",
    projectId: "gold-city-9d670",
    storageBucket: "gold-city-9d670.appspot.com",
    messagingSenderId: "941064344872",
    appId: "1:941064344872:web:0e20f65f93fd8254d36c1d",
    measurementId: "G-B9ZDD9T1LL",
  );
}
