// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
      apiKey: "AIzaSyA-okPckRFVoe6-NK0F1Dl_BJLEqNlwKLs",
      authDomain: "gold-city-9d670.firebaseapp.com",
      projectId: "gold-city-9d670",
      storageBucket: "gold-city-9d670.appspot.com",
      messagingSenderId: "941064344872",
      appId: "1:941064344872:web:0e20f65f93fd8254d36c1d",
      measurementId: "G-B9ZDD9T1LL");

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqfwhizPjWnv4mbM2y-pwE2FF9iC_ScLI',
    appId: '1:941064344872:android:6b3d6a37cd120548d36c1d',
    messagingSenderId: '941064344872',
    projectId: 'gold-city-9d670',
    storageBucket: 'gold-city-9d670.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0qjKVPdwToPrciT0Y3Ek1xsPX70DRCc8',
    appId: '1:941064344872:ios:1ae7f6541b8a7ddcd36c1d',
    messagingSenderId: '941064344872',
    projectId: 'gold-city-9d670',
    storageBucket: 'gold-city-9d670.appspot.com',
    iosClientId:
        '941064344872-53qss7697pbjhm0lhcs1paha8nuk4qnj.apps.googleusercontent.com',
    iosBundleId: 'com.goldcity.goldcityMobil',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0qjKVPdwToPrciT0Y3Ek1xsPX70DRCc8',
    appId: '1:941064344872:ios:8b4c07d7a9b77ea2d36c1d',
    messagingSenderId: '941064344872',
    projectId: 'gold-city-9d670',
    storageBucket: 'gold-city-9d670.appspot.com',
    iosClientId:
        '941064344872-tik6gumst6sbaps050j5t1hh8jfeatlp.apps.googleusercontent.com',
    iosBundleId: 'com.goldcity.goldcity',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA-okPckRFVoe6-NK0F1Dl_BJLEqNlwKLs',
    appId: '1:941064344872:web:bacd536ad6db510fd36c1d',
    messagingSenderId: '941064344872',
    projectId: 'gold-city-9d670',
    authDomain: 'gold-city-9d670.firebaseapp.com',
    storageBucket: 'gold-city-9d670.appspot.com',
    measurementId: 'G-N94SW76JQQ',
  );
}
