// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-okPckRFVoe6-NK0F1Dl_BJLEqNlwKLs',
    appId: '1:941064344872:web:f2e4665cceb92d9dd36c1d',
    messagingSenderId: '941064344872',
    projectId: 'gold-city-9d670',
    authDomain: 'gold-city-9d670.firebaseapp.com',
    storageBucket: 'gold-city-9d670.appspot.com',
    measurementId: 'G-HXXSL6GF9D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqfwhizPjWnv4mbM2y-pwE2FF9iC_ScLI',
    appId: '1:941064344872:android:c719dbc61a94501bd36c1d',
    messagingSenderId: '941064344872',
    projectId: 'gold-city-9d670',
    storageBucket: 'gold-city-9d670.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0qjKVPdwToPrciT0Y3Ek1xsPX70DRCc8',
    appId: '1:941064344872:ios:5aebd45b8763781bd36c1d',
    messagingSenderId: '941064344872',
    projectId: 'gold-city-9d670',
    storageBucket: 'gold-city-9d670.appspot.com',
    iosClientId: '941064344872-4c6mt7g8rr6qjo42jl2tulm7sp8v2q9b.apps.googleusercontent.com',
    iosBundleId: 'com.goldcity.goldcitycondominium',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0qjKVPdwToPrciT0Y3Ek1xsPX70DRCc8',
    appId: '1:941064344872:ios:5aebd45b8763781bd36c1d',
    messagingSenderId: '941064344872',
    projectId: 'gold-city-9d670',
    storageBucket: 'gold-city-9d670.appspot.com',
    iosClientId: '941064344872-4c6mt7g8rr6qjo42jl2tulm7sp8v2q9b.apps.googleusercontent.com',
    iosBundleId: 'com.goldcity.goldcitycondominium',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA-okPckRFVoe6-NK0F1Dl_BJLEqNlwKLs',
    appId: '1:941064344872:web:ace12c063d405480d36c1d',
    messagingSenderId: '941064344872',
    projectId: 'gold-city-9d670',
    authDomain: 'gold-city-9d670.firebaseapp.com',
    storageBucket: 'gold-city-9d670.appspot.com',
    measurementId: 'G-GB8QSQERHT',
  );

}