# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  lane :internal do |options|
    versionNumber = "1.0.0"
    if(options[:version]!=nil)
      versionNumber = options[:version]
    end
    puts versionNumber
    Dir.chdir '../../' do
      sh("flutter build appbundle --release --build-name=#{versionNumber} --build-number=#{versionNumber.to_s}")
    end
    upload_to_play_store(track: 'internal', aab: '../build/app/outputs/bundle/release/app-release.aab')
  end
end
